### ISSUE TITLE
Logo needed

### ISSUE THREAD

**Issue by tamtm** [bminer/node-blade#214]
As title, I think this template engine need a logo

**Comment by richardbmx** [comment]
@tamtm  Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by bminer** [comment]
Sounds cool.  I'd surely welcome some design ideas!  This lib is due to be freshened up at some point soon anyway.

**Comment by richardbmx** [comment]
@bminer  Perfect can you explain to me a bit about what the project is about to make a logo that is in accordance with the project

**Comment by richardbmx** [comment]
@bminer I present this logo proposal for your project based on the name of your project and looking in the readme file that BLADE has. Use the claws of the character in the movie to form a circle of two separate claws placed in a Position that represent the symbols <> and give an identity with HTML.

If you want a change or something different you just have to tell me to do it.

![logo108](https://user-images.githubusercontent.com/35604837/46510608-101e6d80-c818-11e8-9b9b-8a57f8021113.png)

**Comment by bminer** [comment]
@richardbmx - pretty slick! I can dig it for sure. Do you mind if I incorporate these logos into the project? Is it okay to release under MIT license, or do you prefer something else (i.e. Creative Commons)?

**Comment by richardbmx** [comment]
@bminer  perfect if you want that design I can generate a folder with all the necessary files to use it. all my designs are under a Creative Commons license which incorporated a document into the google folder that gives you all the right about the design.

**Comment by bminer** [comment]
The logo definitely has the Wesley Snipes badass feel to it, which I think is important.  Side note, I had a concept at one point which basically featured sunglasses and vampire teeth.  The logo you made seems slightly more fitting and perhaps more professional.

**Comment by richardbmx** [comment]
perfect I'll assemble the folder so you can use the logo and I'll leave the link here

**Comment by richardbmx** [comment]
Here I give you the link with all the necessary files to use the logo, inside you find different variations of the logo to be used in different applications as well as the original files to edit them if you need it. Any questions you can write me I am ready for next projects if you wish

[Google Drive](https://drive.google.com/open?id=1ATdFOi_QX0tmhll8tBo8NSAR5VsRT-kP)

**Comment by richardbmx** [comment]
@bminer  Hello I see that you have not used the logo if you want some change I can do it

**Comment by richardbmx** [comment]
@bminer  If you want I can make a Pull requests for you and so it is easier to incorporate it for you

**Comment by bminer** [comment]
Logo added.  Thanks again, @richardbmx!!!

**Comment by tamtm** [comment]
mission accomplished. Congrats guys 👏
