### ISSUE TITLE
How to include Css File

### ISSUE THREAD

**Issue by jrkk** [bminer/node-blade#215]
I tried different ways, which is not included. please share the which is keyword to use for include the stylesheet in html document.

**Comment by bminer** [comment]
Use the [`link` tag](https://www.w3schools.com/Tags/tag_link.asp).

```
head
  link(rel="stylesheet" type="text/css" href="style.css")
```

**Comment by bminer** [comment]
Feel free to post back here if you have any other questions!  Closing for now.

**Comment by jrkk** [comment]
Its working. thanks
